apiVersion: v1
kind: Service
metadata:
  name: stormtest4-hello-world
spec:
  type: NodePort
  selector:
    run: stormtest4-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000